# name: Ejecutar y Reportar Tests de Playwright

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 3. Construir la imagen de Docker
      run: docker build -t eldiario-tests .

    # --- CAMBIO AQUÍ ---
    - name: 4. Generar el archivo state.json
      run: docker run --rm -u pwuser -v "$(pwd):/app" eldiario-tests mvn compile exec:java -Dexec.mainClass="com.elDiarioTest.setup.Setup"

    # --- Y CAMBIO AQUÍ ---
    - name: 5. Limpiar y ejecutar los tests en Docker
      run: |
        mvn clean
        docker run --rm -u pwuser \
          -v "$(pwd)/target:/app/target" \
          -v "$(pwd)/screenshots:/app/screenshots" \
          eldiario-tests

    - name: 6. Corregir permisos de la carpeta target
      run: sudo chown -R $USER:$USER target

    - name: 7. Generar el reporte de Allure
      run: mvn allure:report

    - name: 8. Subir el reporte de Allure como un artefacto
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin/
