name: Ejecutar y Reportar Tests de Playwright

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. Construir la imagen de Docker
        run: docker build -t eldiario-tests .

      - name: 4. Ejecutar los tests en Docker
        run: |
          mvn clean
          docker run --rm \
            -v "$(pwd)/target:/app/target" \
            -v "$(pwd)/screenshots:/app/screenshots" \
            eldiario-tests

      - name: 5. Corregir permisos de los resultados
        run: sudo chown -R $USER:$USER target

      - name: 6. Generar el reporte de Allure
        run: mvn allure:report

      - name: 7. Subir el reporte de Allure como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/